### ISSUE TITLE
How to plot the "Magnitude vs Frequency" spectrum plot showed in the paper?

### ISSUE THREAD

**Issue by xingchenzhao** [VITA-Group/ViT-Anti-Oversmoothing#1]
Hi, the paper is very amazing. And I wonder can authors release some code about plotting the "Magnitude vs Frequency" in the Fig 2. of the paper?

Thanks!

**Comment by peihaowang** [comment]
Hi Xingchen,

The visualization method is detailed in Appendix F.2. Here is a snippet of example code to plot the spectral response of attention map. Hope you find this helpful.

```
import numpy as np
import math
from scipy.linalg import dft
import matplotlib.pyplot as plt

len_tokens = 197

F = dft(len_tokens, scale='sqrtn')

def calc_spectrum(A):
    return F @ A @ F.T

def plot_spectrum(a):
  s = calc_spectrum(a)
  s = np.linalg.norm(s, ord=2, axis=1)
  s = np.concatenate([s[-math.floor(len_tokens/2):], s[0:1], s[1:math.floor(len_tokens/2)]], axis=0)
  plt.plot(s)
```

Best,
Peihao
