### ISSUE TITLE
How to plot Figure 4 in the paper?

### ISSUE THREAD

**Issue by Yeez-lee** [VITA-Group/ViT-Anti-Oversmoothing#2]
Hi, the paper is quite interesting. And I wonder whether you can provide codes about plotting the _**cosine similarity**_ in the Fig 4. of the paper?

Thanks!

**Comment by Yeez-lee** [comment]
Hi, any hints?

**Comment by peihaowang** [comment]
Hi,

Thanks for you interest. We give the formal definition of cosine similarity in Appendix F.3. Here is a piece of example code that computes the similarity given two batches of tokens. You can specify `x=y` to compute pairwise similarity inside a batch.

```
def compute_similarity(x, y):
    s = torch.matmul(torch.transpose(x, -2, -1), y) # [bs, h, l, l]
    l1, l2 = torch.linalg.norm(x, ord=2, dim=-2), torch.linalg.norm(y, ord=2, dim=-2)
    l = l1[..., :, None] * l2[..., None, :] # [bs, h, l, l]
    N = s.shape[-1]
    s = torch.abs(s / l)
    return s.mean().item()
```
Best,
Peihao
