### ISSUE TITLE
FLOPs about the attention scale

### ISSUE THREAD

**Issue by techmonsterwang** [VITA-Group/ViT-Anti-Oversmoothing#4]
Hi, Peihao. Thanls for the nice work. 

The flops calculation code can be found at attn_scale.py:

    def flops(self, N):
        # calculate flops for 1 window with token length of N
        flops = 0
        # qkv = self.qkv(x)
        flops += N * self.dim * 3 * self.dim
        # attn = (q @ k.transpose(-2, -1))
        flops += self.num_heads * N * (self.dim // self.num_heads) * N
        # attnscale
        flops += self.num_heads * N * N
        #  x = (attn @ v)
        flops += self.num_heads * N * N * (self.dim // self.num_heads)
        # x = self.proj(x)
        flops += N * self.dim * self.dim
        return flops

1. is the computational effort of scale and softmax being ignored?

2. is the computation of the averaging operation for attn_d ignored?

Thanks for your reply. :-)

**Comment by peihaowang** [comment]
Hi Jiahao,

Thanks for this good question. This piece of code is mostly adopted from SwinTransformer with one line added for AttnScale. The AttnScale can be regarded as a linear combination between the original attention map and a fixed matrix, so its complexity should be $O(H N^2)$. Hope you find this useful.

Peihao

**Comment by techmonsterwang** [comment]
Thanks for the reply. 

It seems like flops += self.num_heads * N * N correspronds to Eq.9 in the paper, and the computation of Eq.7 (mean operation) is ignored?

**Comment by peihaowang** [comment]
Hi Jiahao,

I have re-examined the code. I guess what you suggested here is correct. The AttnScale has two steps:

1. Decomposes a high-pass filter, which takes num_heads * N * N
2. Rescale and merge two components. This takes 2 * num_heads * N * N.

This enlarges the flops in that step by a constant. I will update the code and numbers in the paper later.

Peihao
