### ISSUE TITLE
How can i visualise the spectrum of the attention maps?

### ISSUE THREAD

**Issue by EatonL** [VITA-Group/ViT-Anti-Oversmoothing#5]
I really enjoyed your paper, and i would like to know how to get the figure 5 in your paper.I have tried the scipy.signal.freqz function but the results are very different from yours. I would be grateful if you could help me with the code.

**Comment by peihaowang** [comment]
Hi Eaton,

Thanks for your interest and sorry for the late reply. I hope the discussion in this thread https://github.com/VITA-Group/ViT-Anti-Oversmoothing/issues/1#issuecomment-1037541922 could be helpful for you.

Best,
Peihao
