### ISSUE TITLE
About FeatScale's code

### ISSUE THREAD

**Issue by mcshih** [VITA-Group/ViT-Anti-Oversmoothing#6]
Hello, I have a question about the implementation.
In the featscale.py line 53-55
```
        x_attn = x_attn + x_d + x_h

        x = x + self.drop_path(x_attn + x_d + x_h)
```
You add x_d & x_h twice.
Why does the implementation need to be done this way? Is there any special purpose?

**Comment by peihaowang** [comment]
Hi,

Thanks for reaching out. There is no special reason to add `x_d` and `x_h` twice but just to make the architecture compatible with the pre-trained checkpoint. I presume removing either 53 or 55 can produce similar performance.

Best,
Peihao
