### ISSUE TITLE
Cosine Similarity Graph

### ISSUE THREAD

**Issue by edwintenagyei367** [VITA-Group/ViT-Anti-Oversmoothing#7]
Hi ,thank you very much for the wonderful work.
I am wondering how the implementation of the cosine similarity graphs in the paper was done.I would appreciate if i can get a code implementation for that.

**Comment by peihaowang** [comment]
Hi,

Apologies for my late response. Similar questions have been answered here: #2 #5. Hope you find them helpful.

Best,
Peihao
